import Footer from "@/components/footer/Footer"
import Navbar from "@/components/navbar/Nvabar"
import "./global.css"
import "./../node_modules/bootstrap/dist/css/bootstrap-grid.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     <body>
       <div className="container">
         <Navbar />
       {children}
       <Footer />
       </div>
     </body>
     
    </html>
  )
}
